#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hook"

git add -A .

npm run build && npm run lint|| (
  echo "Build failed. ❌ "
  exit 1
)
echo "Build completed successfully. ✅ "